name = "sui-rpc-hub"
main = "src/index.ts"
compatibility_date = "2026-05-01"
workers_dev = true

routes = [
  { pattern = "sui-rpc.bithub.pro", zone_id = "a2377099496ecf3fe85caa580e64b070" }
]

[vars]
CHAIN = "sui"
CACHE_ENABLED = "true"
RPC_TIMEOUT = "10000"
